language: node_js
node_js:
  - "0.10"
before_script:
  - node -e "var connect = require('connect'); connect.createServer(connect.static(process.cwd())).listen(8080);" &
script:
  - node_modules/mocha-phantomjs/bin/mocha-phantomjs http://localhost:8080/test/index.html